services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3007:80"
    networks:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8007:3000"
    depends_on:
      - postgres
      - api
    environment:
      - API_END_POINT=http://api:5007
    networks:
      - client

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5007:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pg-db
      - client

  postgres:
    image: postgres
    restart: always
    ports:
      - "7007:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  client:
  pg-db:

volumes:
  pgdata:
