import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_Thai_Looped } from "next/font/google";

const notoSansThaiLooped = Noto_Sans_Thai_Looped({
  subsets: ["thai"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansThaiLooped.className}>{children}</body>
    </html>
  );
}
